2020/07/13/Building a Food Tracker App in Flask/foodtracker/foodtracker/models.py
from .extensions import db


log_food = db.Table('log_food',
    db.Column('log_id', db.Integer, db.ForeignKey('log.id'), primary_key=True),
    db.Column('food_id', db.Integer, db.ForeignKey('food.id'), primary_key=True)
)

class Food(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    proteins = db.Column(db.Integer, nullable=False)
    carbs = db.Column(db.Integer, nullable=False)
    fats = db.Column(db.Integer, nullable=False)

    @property
    def calories(self):
        return self.proteins * 4 + self.carbs * 4 + self.fats * 9

class Log(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date, nullable=False)
    foods = db.relationship('Food', secondary=log_food, lazy='dynamic')

2020/07/13/Building a Food Tracker App in Flask/foodtracker/foodtracker/__init__.py
from flask import Flask 

from .main.routes import main
from .extensions import db

def create_app():
    app = Flask(__name__)

    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite3'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)

    app.register_blueprint(main)

    return app

2020/07/13/Building a Food Tracker App in Flask/foodtracker/foodtracker/main/routes.py
from flask import Blueprint, render_template, request, redirect, url_for

from foodtracker.models import Food, Log
from foodtracker.extensions import db

from datetime import datetime 

main = Blueprint('main', __name__)

@main.route('/')
def index():
    logs = Log.query.order_by(Log.date.desc()).all()

    log_dates = []

    for log in logs:
        proteins = 0
        carbs = 0
        fats = 0
        calories = 0

        for food in log.foods:
            proteins += food.proteins
            carbs += food.carbs 
            fats += food.fats
            calories += food.calories

        log_dates.append({
            'log_date' : log,
            'proteins' : proteins,
            'carbs' : carbs,
            'fats' : fats,
            'calories' : calories
        })

    return render_template('index.html', log_dates=log_dates)

@main.route('/create_log', methods=['POST'])
def create_log():
    date = request.form.get('date')

    log = Log(date=datetime.strptime(date, '%Y-%m-%d'))

    db.session.add(log)
    db.session.commit()

    return redirect(url_for('main.view', log_id=log.id))

@main.route('/add')
def add():
    foods = Food.query.all()

    return render_template('add.html', foods=foods, food=None)

@main.route('/add', methods=['POST'])
def add_post():
    food_name = request.form.get('food-name')
    proteins = request.form.get('protein')
    carbs = request.form.get('carbohydrates')
    fats = request.form.get('fat')

    food_id = request.form.get('food-id')

    if food_id:
        food = Food.query.get_or_404(food_id)
        food.name = food_name
        food.proteins = proteins
        food.carbs = carbs
        food.fats = fats

    else:
        new_food = Food(
            name=food_name,
            proteins=proteins, 
            carbs=carbs, 
            fats=fats
        )
    
        db.session.add(new_food)

    db.session.commit()

    return redirect(url_for('main.add'))

@main.route('/delete_food/<int:food_id>')
def delete_food(food_id):
    food = Food.query.get_or_404(food_id)
    db.session.delete(food)
    db.session.commit()

    return redirect(url_for('main.add'))

@main.route('/edit_food/<int:food_id>')
def edit_food(food_id):
    food = Food.query.get_or_404(food_id)
    foods = Food.query.all()

    return render_template('add.html', food=food, foods=foods)
    
@main.route('/view/<int:log_id>')
def view(log_id):
    log = Log.query.get_or_404(log_id)

    foods = Food.query.all()

    totals = {
        'protein' : 0,
        'carbs' : 0,
        'fat' : 0,
        'calories' : 0
    }

    for food in log.foods:
        totals['protein'] += food.proteins
        totals['carbs'] += food.carbs
        totals['fat'] += food.fats 
        totals['calories'] += food.calories

    return render_template('view.html', foods=foods, log=log, totals=totals)

@main.route('/add_food_to_log/<int:log_id>', methods=['POST'])
def add_food_to_log(log_id):
    log = Log.query.get_or_404(log_id)

    selected_food = request.form.get('food-select')

    food = Food.query.get(int(selected_food))

    log.foods.append(food)
    db.session.commit()

    return redirect(url_for('main.view', log_id=log_id))

@main.route('/remove_food_from_log/<int:log_id>/<int:food_id>')
def remove_food_from_log(log_id, food_id):
    log = Log.query.get(log_id)
    food = Food.query.get(food_id)

    log.foods.remove(food)
    db.session.commit()

    return redirect(url_for('main.view', log_id=log_id))

2020/07/13/Building a Food Tracker App in Flask/foodtracker/foodtracker/templates/add.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Food Tracker | Add Food Item</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">
			
			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{ url_for('main.index') }}">FOOD TRACKER</a>
					</h1>
					
					<div class="row t20">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
							  <li role="presentation">
							  	<a href="{{ url_for('main.index') }}" title="Home">Home</a>
							  </li>
							  <li role="presentation" class="active">
							  	<a href="{{ url_for('main.add') }}" title="Add Food Item">Add Food Item</a>
							  </li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="lean-h text-black">
								<i class="glyphicon glyphicon-plus-sign"></i> New Food Form
							</h3>
							<hr />

							<form action="{{ url_for('main.add') }}" method="POST" role="form">
							
								<div class="row">
									<div class="col-lg-4">
										<div class="form-group">
											<label for="food-name">Food Name</label>
						                  	<input type="text" class="form-control" id="food-name" name="food-name" placeholder="Food Name" value="{{ food.name }}" autofocus>
										</div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
						                  <label for="protein">Protein</label>
						                  <input type="number" class="form-control" id="protein" name="protein" placeholder="Protein" value="{{ food.proteins }}">
						                </div>
									</div>
									<div class="col-lg-4">
										<div class="form-group">
						                  <label for="carbohydrates">Carbohydrates</label>
						                  <input type="number" class="form-control" id="carbohydrates" name="carbohydrates" placeholder="Carbohydrates" value="{{ food.carbs }}">
						                </div>
									</div>
								</div>

								<div class="row">
									<div class="col-lg-4">
										<div class="form-group">
						                  <label for="fat">Fat</label>
						                  <input type="number" class="form-control" id="fat" name="fat" placeholder="Fat" value="{{ food.fats }}">
						                </div>
									</div>

									<div class="col-lg-4">
										<div class="form-group">
											<label style="visibility:hidden">submit</label>
											<input type="hidden" name="food-id" value="{{ food.id }}" >
											<button type="submit" class="btn btn-primary btn-block">
												<i class="glyphicon glyphicon-upload"></i> Submit
											</button>
										</div>
									</div>
								</div>
							
							</form>	
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h4 class="lean-h text-black">
								<i class="glyphicon glyphicon-th-list"></i> Existing Food Items
							</h4>
						</div>
						<div class="table-responsive">
							<table class="table table-striped table-hover table-bordered">
								<thead>
									<tr>
										<th style="width: 5%;">#</th>
										<th>Name</th>
										<th style="width: 10%;">Protein</th>
										<th style="width: 16%;">Carbohydrates</th>
										<th style="width: 10%;">Fat</th>
										<th style="width: 12%;">Calories</th>
										<th style="width: 20%;">Actions</th>
									</tr>
								</thead>
								<tbody>
									{% for food in foods %}
									<tr>
										<td>{{ food.id }}</td><td>{{ food.name }}</td><td>{{ food.proteins }}</td>
										<td>{{ food.carbs }}</td><td>{{ food.fats }}</th><td>{{ food.calories }}</td>
										<td>
											<a href="{{ url_for('main.edit_food', food_id=food.id) }}" class="btn btn-default btn-xs">
												<i class="glyphicon glyphicon-pencil"></i> Edit
											</a> 
											<a href="{{ url_for('main.delete_food', food_id=food.id) }}" class="btn btn-danger btn-xs">
												<i class="glyphicon glyphicon-trash"></i> Delete
											</a> 
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2017 <strong>Food Tracker</strong>
					</div>
				</div>
			</footer>

		</div>

		<!-- jQuery -->
		<script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>
	</body>
</html>

2020/07/13/Building a Food Tracker App in Flask/foodtracker/foodtracker/templates/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Food Tracker | Home</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">
			
			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{ url_for('main.index') }}">FOOD TRACKER</a>
					</h1>
					
					<div class="row t20">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
							  <li role="presentation" class="active">
							  	<a href="{{ url_for('main.index') }}" title="Home">Home</a>
							  </li>
							  <li role="presentation">
							  	<a href="{{ url_for('main.add') }}" title="Add Food Item">Add Food Item</a>
							  </li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-4 col-lg-offset-4">
					<div class="panel panel-default">
						<div class="panel-body">
							<form action="{{ url_for('main.create_log') }}" method="POST" role="form">
							
								<div class="form-group">
									<label><i class="glyphicon glyphicon-plus-sign"></i> Add New Date</label>
									<div class="input-group">
									  <input type="date" class="form-control" name="date" placeholder="Select New Date" aria-label="date" aria-describedby="add-btn">
									  <span class="input-group-btn">
										<button type="submit" class="btn btn-primary" id="add-btn">
										  <i class="glyphicon glyphicon-plus-sign"></i> Add Date
										</button>
									  </span>
									</div>
								</div>
							
							</form>	
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-12">
					<h4 class="text-center text-white"><strong>Existing Records ({{ log_dates|length }})</strong></h4>
				</div>
			</div>

			{% for row in log_dates|batch(4) %}
			<div class="row t20">
				{% for log_date in row %}
				<div class="col-lg-3">
					<div class="panel panel-warning">
						<div class="panel-body text-bold">
							<i class="glyphicon glyphicon-calendar"></i> {{ log_date['log_date'].date.strftime('%B %d, %Y') }}

							<a class="btn btn-primary btn-xs pull-right" href="{{ url_for('main.view', log_id=log_date['log_date'].id) }}">
								View <i class="glyphicon glyphicon-arrow-right"></i>
							</a>
						</div>
						<ul class="list-group">
							<li class="list-group-item text-bold"><span class="badge">{{ log_date['proteins'] }}</span> Protein</li>
							<li class="list-group-item text-bold"><span class="badge">{{ log_date['carbs'] }}</span> Carbohydrate</li>
							<li class="list-group-item text-bold"><span class="badge">{{ log_date['fats'] }}</span> Fat</li>
							<li class="list-group-item text-bold"><span class="badge">{{ log_date['calories'] }}</span> Calories</li>
						</ul>
					</div>
				</div>
				{% endfor %}
			</div>
			{% endfor %}

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2017 <strong>Food Tracker</strong>
					</div>
				</div>
			</footer>

		</div>

		<!-- jQuery -->
		<script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>
	</body>
</html>

2020/07/13/Building a Food Tracker App in Flask/foodtracker/foodtracker/templates/view.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Food Tracker | View Details</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}" />
		<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>

		<div class="container-fluid" id="wrapper">
			
			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{ url_for('main.index') }}">FOOD TRACKER</a>
					</h1>
					
					<div class="row t20">
						<div class="col-lg-4 col-lg-offset-4">
							<ul class="nav nav-pills nav-justified">
							  <li role="presentation">
							  	<a href="{{ url_for('main.index') }}" title="Home">Home</a>
							  </li>
							  <li role="presentation">
							  	<a href="{{ url_for('main.add') }}" title="Add Food Item">Add Food Item</a>
							  </li>
							</ul>
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-4 col-lg-offset-4">
					<div class="panel panel-default">
						<div class="panel-body">
							<form action="{{ url_for('main.add_food_to_log', log_id=log.id) }}" method="POST" role="form">
							
								<div class="form-group">
									<label>Add Food</label>
									<div class="input-group">
									  <select class="form-control" name="food-select">
										  {% for food in foods %}     
											<option value="{{ food.id }}">{{ food.name }}</option>
									      {% endfor %}
					                    </select>
									  <span class="input-group-btn">
										<button type="submit" class="btn btn-primary" id="add-btn">
										  <i class="glyphicon glyphicon-plus-sign"></i> Add Food
										</button>
									  </span>
									</div>
								</div>
							
							</form>	
						</div>
					</div>
				</div>
			</div>

			<div class="row t20">
				<div class="col-lg-8 col-lg-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="lean-h text-black">
								<i class="glyphicon glyphicon-calendar"></i> {{ log.date.strftime('%B %d, %Y') }}
							</h3>

							<div class="row">
								<div class="col-lg-3">
									<h4 class="lean-h">
										Protein: &nbsp;<strong class="f25">{{ totals['protein'] }}</strong>
									</h4>
								</div>
								<div class="col-lg-3">
									<h4 class="lean-h">
										Carbohydrates: <strong class="f25">{{ totals['carbs'] }}</strong>
									</h4>
								</div>
								<div class="col-lg-3">
									<h4 class="lean-h">
										Fat: <strong class="f25">{{ totals['fat'] }}</strong>
									</h4>
								</div>
								<div class="col-lg-3">
									<h4 class="lean-h">
										Calories: <strong class="f25">{{ totals['calories'] }}</strong>
									</h4>
								</div>
							</div>
						</div>
						<div class="table-responsive">
							<table class="table table-striped table-hover table-bordered">
								<thead>
									<tr>
										<th style="width: 5%;">#</th>
										<th>Name</th>
										<th style="width: 10%;">Protein</th>
										<th style="width: 16%;">Carbohydrates</th>
										<th style="width: 10%;">Fat</th>
										<th style="width: 12%;">Calories</th>
										<th style="width: 20%;">Actions</th>
									</tr>
								</thead>
								<tbody>
									{% for food in log.foods %}
									<tr>
										<td>{{ loop.index }}</td><td>{{ food.name }}</td><td>{{ food.proteins }}</td>
										<td>{{ food.carbs }}</td><td>{{ food.fats }}</th><td>{{ food.calories }}</td>
										<td>
											<a href="{{ url_for('main.remove_food_from_log', log_id=log.id, food_id=food.id) }}" class="btn btn-danger btn-xs">
												<i class="glyphicon glyphicon-trash"></i> Delete
											</a> 
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2017 <strong>Food Tracker</strong>
					</div>
				</div>
			</footer>

		</div>

		<!-- jQuery -->
		<script src="{{ url_for('static', filename='bs/js/jquery.min.js') }}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{ url_for('static', filename='bs/js/bootstrap.min.js') }}"></script>
	</body>
</html>